#!/usr/bin/env bash

ln -sf ~/.cache/wal/colors-kitty.conf ~/.config/kitty/kitty.conf
ln -sf ~/.cache/wal/colors-waybar.css ~/.config/waybar/style.css
#ln -sf ~/.cache/wal/colors-vscdoium.json ~/.config/vscodium/
ln -sf ~/.cache/wal/colors-rofi-dark.rasi ~/.config/rofi/
#ln -sf ~/.cache/wal/

#rekiad qutebrowser if open
pgrep qutebrowser > /dev/null && qutebrowser ':config-source' #refresh qute if running

#reload waybar
pkill waybar
sleep 0.2
waybar &

#reload hyprland
hyprctl reload

notify-send "Wallpaper and colorscheme changed; setting rgb value"
sudo openrgb --noautoconnect -c $(tail -c +2 ~/.cache/wal/colors) -b 65
 hang
